name: Update Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}        

      - name: Install dependencies
        run: npm ci          

      - name: Checkout Framework
        uses: actions/checkout@v4
        with:
          repository: gtscio/framework
          path: framework

      - name: Copy Docs to Framework
        run: |
          rm -rf framework/docs/packages/nameof
          cp -r framework/packages/nameof/dist/docs/* docs/packages/nameof

      - name: Build
        run: npm run build