name: Update Documentation from Packages Main

env:
  gha-branch: main

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs
        uses: actions/checkout@v4
        with:
          ref: ${{ env.gha-branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Checkout Framework
        uses: actions/checkout@v4
        with:
          repository: gtscio/framework
          path: import-packages/framework
          ref: ${{ env.gha-branch }}
          token: ${{ secrets.GH_PAT }}

      - name: Copy Framework to Docs
        run: |
          PACKAGES=$(jq -r '.packages | map(.name) | "\"" + join("\" \"") + "\"" | @sh' import-packages/framework/docs/packages.json)
          echo $PACKAGES

          for pkg in "${PACKAGES[@]}"
          do
            rm -rf docs/packages/$pkg
            cp -r import-packages/framework/packages/$pkg/docs docs/packages/$pkg
          done

          cp import-packages/framework/docs/packages.json docs/packages/framework.json
          rm -r import-packages/framework

      - name: Build
        run: npm run build

      - name: Create Pull Request
        run: |
          git checkout -b docs/update-${{ env.gha-branch }}-${{ github.sha }}
          git config --global user.name 'GTSC'
          git config --global user.email 'ci@gtsc.io'
          git add .
          git commit -am "Update Packages Documentation"
          git push --set-upstream origin docs/update-${{ env.gha-branch }}-${{ github.sha }}
          # Enable GitHub Actions Read and write permissions under Settings > Actions
          # Allow GitHub Actions to create and approve pull requests under Settings > Actions
          gh pr create -B ${{ env.gha-branch }} -H docs/update-${{ env.gha-branch }}-${{ github.sha }} --title 'Merge packages documentation into ${{ env.gha-branch }}' --body 'Merges the docs from the packages into ${{ env.gha-branch }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
